#!/usr/local/bin/python

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def get_fibonacci_numers(cap):
	a=1
	b=1

	fib_numbers = [1,1]

	while True:
		next_fib = a + b

		if next_fib > cap

		fib_numbers.append(next_fib)

		a = b
		b = next_fib

	return fib_numbers


running_sum = 0

for fib_num in get_fibonacci_numers(4000000):
	if fib_num % 2 == 0:
		running_sum += fib_num

print running_sum


